In [28]:
import pandas as pd

df = pd.read_csv('../../data/lung_cancer_dataset.csv')

In [29]:
df

,patient_id,age,gender,pack_years,radon_exposure,asbestos_exposure,secondhand_smoke_exposure,copd_diagnosis,alcohol_consumption,family_history,lung_cancer
0,100000,69,Male,66.025244,High,No,No,Yes,Moderate,No,No
1,100001,32,Female,12.780800,High,No,Yes,Yes,Moderate,Yes,Yes
2,100002,89,Female,0.408278,Medium,Yes,Yes,Yes,NaN,No,Yes
3,100003,78,Female,44.065232,Low,No,Yes,No,Moderate,No,Yes
4,100004,38,Female,44.432440,Medium,Yes,No,Yes,NaN,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...
49995,149995,81,Female,9.386431,Medium,No,Yes,No,Moderate,No,Yes
49996,149996,28,Male,99.471718,Medium,No,Yes,No,Moderate,No,Yes
49997,149997,90,Male,14.349722,Low,Yes,Yes,No,Heavy,Yes,Yes
49998,149998,33,Female,87.012555,Medium,No,No,Yes,Moderate,No,No
49999,149999,31,Male,37.596851,Low,No,No,Yes,NaN,Yes,Yes

In [30]:
cancer = df[df['lung_cancer'] == "Yes"]["age"]
no_cancer = df[df['lung_cancer'] == "No"]["age"]

In [31]:
print("Mean age, cancer:", cancer.mean())
print("Mean age, no cancer:", no_cancer.mean())

Mean age, cancer: 60.81148876731463
Mean age, no cancer: 54.56165259657201

In [32]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(cancer, no_cancer, equal_var=False)
print("T-statistic:", t_stat)
print("P-value:", p_value) # Tells us that there is a significant difference between the two groups. The p-value is less than 0.05, which means we can reject the null hypothesis that there is no difference in mean age between those with and without lung cancer.

T-statistic: 27.03638652367475
P-value: 4.665853197372571e-159

In [33]:
# what proportion of the patients have a family history of lung cancer?

family_history_proportion = df['family_history'].value_counts()
print("Proportion of patients with family history of lung cancer:", family_history_proportion)

Proportion of patients with family history of lung cancer: family_history
No     25017
Yes    24983
Name: count, dtype: int64

In [34]:
import numpy as np

p0 = 0.5 # Null hypothesis proportion
n = len(df) # Sample size

SE = np.sqrt(p0 * (1 - p0) / n)

print("Standard Error:", SE)

Standard Error: 0.00223606797749979

In [35]:
p_hat = family_history_proportion['Yes'] / n
z_stat = (p_hat - p0) / SE
print("Z-Statistic:", z_stat)

Z-Statistic: -0.1520526224699888

In [36]:
t_stat, p_value = ttest_ind(cancer, no_cancer, equal_var=False)
print("T-statistic:", t_stat)
print("P-value:", p_value) # Tells us that there is a significant difference between

T-statistic: 27.03638652367475
P-value: 4.665853197372571e-159

In [37]:
table = pd.crosstab(df['lung_cancer'], df['family_history'])
table

family_history     No    Yes
lung_cancer
No               9062   6574
Yes             15955  18409

In [38]:
from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(table)
print("Chi-squared Statistic:", chi2)
print("P-value:", p_value) # Tells us that there is a significant association between
print("Degrees of Freedom:", dof)
print("Expected Frequencies:")
print(expected)


# What is the null hypothesis for the chi-squared test?
# A: The null hypothesis for the chi-squared test is that there is no association between lung cancer and family history of lung cancer. In other words, the two variables are independent of each other.

Chi-squared Statistic: 570.6515896228648
P-value: 4.0511522959651226e-126
Degrees of Freedom: 1
Expected Frequencies:
[[ 7823.31624  7812.68376]
 [17193.68376 17170.31624]]

In [39]:
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between lung cancer and family history of lung cancer.")
else:
    print("Fail to reject the null hypothesis: There is no significant association between lung cancer and family history of lung cancer.")

Reject the null hypothesis: There is a significant association between lung cancer and family history of lung cancer.

In [40]:
df["gender"].head(10)

0      Male
1    Female
2    Female
3    Female
4    Female
5      Male
6      Male
7      Male
8    Female
9      Male
Name: gender, dtype: str

In [41]:
df["gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

gender_encoded = encoder.fit_transform(df[["gender"]])

In [48]:
gender_encoded[:10]  # Display the first 10 rows of the encoded gender data

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])